<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class InsertCountries extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @link https://gist.github.com/kcak11/4a2f22fb8422342b3b3daa7a1965f4e4#file-countries-json
     * @return void
     */
    public function run()
    {
      $countries = [
          0 => [
            'name' => 'Afghanistan',
            'dialCode' => '+93',
            'isoCode' => 'AF',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/af.svg',
          ],
          1 => [
            'name' => 'Aland Islands',
            'dialCode' => '+358',
            'isoCode' => 'AX',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ax.svg',
          ],
          2 => [
            'name' => 'Albania',
            'dialCode' => '+355',
            'isoCode' => 'AL',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/al.svg',
          ],
          3 => [
            'name' => 'Algeria',
            'dialCode' => '+213',
            'isoCode' => 'DZ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/dz.svg',
          ],
          4 => [
            'name' => 'American Samoa',
            'dialCode' => '+1684',
            'isoCode' => 'AS',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/as.svg',
          ],
          5 => [
            'name' => 'Andorra',
            'dialCode' => '+376',
            'isoCode' => 'AD',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ad.svg',
          ],
          6 => [
            'name' => 'Angola',
            'dialCode' => '+244',
            'isoCode' => 'AO',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ao.svg',
          ],
          7 => [
            'name' => 'Anguilla',
            'dialCode' => '+1264',
            'isoCode' => 'AI',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ai.svg',
          ],
          8 => [
            'name' => 'Antarctica',
            'dialCode' => '+672',
            'isoCode' => 'AQ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/aq.svg',
          ],
          9 => [
            'name' => 'Antigua and Barbuda',
            'dialCode' => '+1268',
            'isoCode' => 'AG',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ag.svg',
          ],
          10 => [
            'name' => 'Argentina',
            'dialCode' => '+54',
            'isoCode' => 'AR',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ar.svg',
          ],
          11 => [
            'name' => 'Armenia',
            'dialCode' => '+374',
            'isoCode' => 'AM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/am.svg',
          ],
          12 => [
            'name' => 'Aruba',
            'dialCode' => '+297',
            'isoCode' => 'AW',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/aw.svg',
          ],
          13 => [
            'name' => 'Ascension Island',
            'dialCode' => '+247',
            'isoCode' => 'AC',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ac.svg',
          ],
          14 => [
            'name' => 'Australia',
            'dialCode' => '+61',
            'isoCode' => 'AU',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/au.svg',
          ],
          15 => [
            'name' => 'Austria',
            'dialCode' => '+43',
            'isoCode' => 'AT',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/at.svg',
          ],
          16 => [
            'name' => 'Azerbaijan',
            'dialCode' => '+994',
            'isoCode' => 'AZ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/az.svg',
          ],
          17 => [
            'name' => 'Bahamas',
            'dialCode' => '+1242',
            'isoCode' => 'BS',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bs.svg',
          ],
          18 => [
            'name' => 'Bahrain',
            'dialCode' => '+973',
            'isoCode' => 'BH',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bh.svg',
          ],
          19 => [
            'name' => 'Bangladesh',
            'dialCode' => '+880',
            'isoCode' => 'BD',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bd.svg',
          ],
          20 => [
            'name' => 'Barbados',
            'dialCode' => '+1246',
            'isoCode' => 'BB',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bb.svg',
          ],
          21 => [
            'name' => 'Belarus',
            'dialCode' => '+375',
            'isoCode' => 'BY',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/by.svg',
          ],
          22 => [
            'name' => 'Belgium',
            'dialCode' => '+32',
            'isoCode' => 'BE',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/be.svg',
          ],
          23 => [
            'name' => 'Belize',
            'dialCode' => '+501',
            'isoCode' => 'BZ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bz.svg',
          ],
          24 => [
            'name' => 'Benin',
            'dialCode' => '+229',
            'isoCode' => 'BJ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bj.svg',
          ],
          25 => [
            'name' => 'Bermuda',
            'dialCode' => '+1441',
            'isoCode' => 'BM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bm.svg',
          ],
          26 => [
            'name' => 'Bhutan',
            'dialCode' => '+975',
            'isoCode' => 'BT',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bt.svg',
          ],
          27 => [
            'name' => 'Bolivia',
            'dialCode' => '+591',
            'isoCode' => 'BO',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bo.svg',
          ],
          28 => [
            'name' => 'Bosnia and Herzegovina',
            'dialCode' => '+387',
            'isoCode' => 'BA',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ba.svg',
          ],
          29 => [
            'name' => 'Botswana',
            'dialCode' => '+267',
            'isoCode' => 'BW',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bw.svg',
          ],
          30 => [
            'name' => 'Brazil',
            'dialCode' => '+55',
            'isoCode' => 'BR',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/br.svg',
          ],
          31 => [
            'name' => 'British Indian Ocean Territory',
            'dialCode' => '+246',
            'isoCode' => 'IO',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/io.svg',
          ],
          32 => [
            'name' => 'Brunei Darussalam',
            'dialCode' => '+673',
            'isoCode' => 'BN',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bn.svg',
          ],
          33 => [
            'name' => 'Bulgaria',
            'dialCode' => '+359',
            'isoCode' => 'BG',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bg.svg',
          ],
          34 => [
            'name' => 'Burkina Faso',
            'dialCode' => '+226',
            'isoCode' => 'BF',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bf.svg',
          ],
          35 => [
            'name' => 'Burundi',
            'dialCode' => '+257',
            'isoCode' => 'BI',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bi.svg',
          ],
          36 => [
            'name' => 'Cambodia',
            'dialCode' => '+855',
            'isoCode' => 'KH',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/kh.svg',
          ],
          37 => [
            'name' => 'Cameroon',
            'dialCode' => '+237',
            'isoCode' => 'CM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/cm.svg',
          ],
          38 => [
            'name' => 'Canada',
            'dialCode' => '+1',
            'isoCode' => 'CA',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ca.svg',
          ],
          39 => [
            'name' => 'Cape Verde',
            'dialCode' => '+238',
            'isoCode' => 'CV',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/cv.svg',
          ],
          40 => [
            'name' => 'Cayman Islands',
            'dialCode' => '+1345',
            'isoCode' => 'KY',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ky.svg',
          ],
          41 => [
            'name' => 'Central African Republic',
            'dialCode' => '+236',
            'isoCode' => 'CF',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/cf.svg',
          ],
          42 => [
            'name' => 'Chad',
            'dialCode' => '+235',
            'isoCode' => 'TD',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/td.svg',
          ],
          43 => [
            'name' => 'Chile',
            'dialCode' => '+56',
            'isoCode' => 'CL',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/cl.svg',
          ],
          44 => [
            'name' => 'China',
            'dialCode' => '+86',
            'isoCode' => 'CN',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/cn.svg',
          ],
          45 => [
            'name' => 'Christmas Island',
            'dialCode' => '+61',
            'isoCode' => 'CX',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/cx.svg',
          ],
          46 => [
            'name' => 'Cocos (Keeling) Islands',
            'dialCode' => '+61',
            'isoCode' => 'CC',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/cc.svg',
          ],
          47 => [
            'name' => 'Colombia',
            'dialCode' => '+57',
            'isoCode' => 'CO',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/co.svg',
          ],
          48 => [
            'name' => 'Comoros',
            'dialCode' => '+269',
            'isoCode' => 'KM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/km.svg',
          ],
          49 => [
            'name' => 'Congo',
            'dialCode' => '+242',
            'isoCode' => 'CG',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/cg.svg',
          ],
          50 => [
            'name' => 'Cook Islands',
            'dialCode' => '+682',
            'isoCode' => 'CK',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ck.svg',
          ],
          51 => [
            'name' => 'Costa Rica',
            'dialCode' => '+506',
            'isoCode' => 'CR',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/cr.svg',
          ],
          52 => [
            'name' => 'Croatia',
            'dialCode' => '+385',
            'isoCode' => 'HR',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/hr.svg',
          ],
          53 => [
            'name' => 'Cuba',
            'dialCode' => '+53',
            'isoCode' => 'CU',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/cu.svg',
          ],
          54 => [
            'name' => 'Cyprus',
            'dialCode' => '+357',
            'isoCode' => 'CY',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/cy.svg',
          ],
          55 => [
            'name' => 'Czech Republic',
            'dialCode' => '+420',
            'isoCode' => 'CZ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/cz.svg',
          ],
          56 => [
            'name' => 'Democratic Republic of the Congo',
            'dialCode' => '+243',
            'isoCode' => 'CD',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/cd.svg',
          ],
          57 => [
            'name' => 'Denmark',
            'dialCode' => '+45',
            'isoCode' => 'DK',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/dk.svg',
          ],
          58 => [
            'name' => 'Djibouti',
            'dialCode' => '+253',
            'isoCode' => 'DJ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/dj.svg',
          ],
          59 => [
            'name' => 'Dominica',
            'dialCode' => '+1767',
            'isoCode' => 'DM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/dm.svg',
          ],
          60 => [
            'name' => 'Dominican Republic',
            'dialCode' => '+1849',
            'isoCode' => 'DO',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/do.svg',
          ],
          61 => [
            'name' => 'Ecuador',
            'dialCode' => '+593',
            'isoCode' => 'EC',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ec.svg',
          ],
          62 => [
            'name' => 'Egypt',
            'dialCode' => '+20',
            'isoCode' => 'EG',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/eg.svg',
          ],
          63 => [
            'name' => 'El Salvador',
            'dialCode' => '+503',
            'isoCode' => 'SV',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sv.svg',
          ],
          64 => [
            'name' => 'Equatorial Guinea',
            'dialCode' => '+240',
            'isoCode' => 'GQ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gq.svg',
          ],
          65 => [
            'name' => 'Eritrea',
            'dialCode' => '+291',
            'isoCode' => 'ER',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/er.svg',
          ],
          66 => [
            'name' => 'Estonia',
            'dialCode' => '+372',
            'isoCode' => 'EE',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ee.svg',
          ],
          67 => [
            'name' => 'Eswatini',
            'dialCode' => '+268',
            'isoCode' => 'SZ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sz.svg',
          ],
          68 => [
            'name' => 'Ethiopia',
            'dialCode' => '+251',
            'isoCode' => 'ET',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/et.svg',
          ],
          69 => [
            'name' => 'Falkland Islands (Malvinas)',
            'dialCode' => '+500',
            'isoCode' => 'FK',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/fk.svg',
          ],
          70 => [
            'name' => 'Faroe Islands',
            'dialCode' => '+298',
            'isoCode' => 'FO',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/fo.svg',
          ],
          71 => [
            'name' => 'Fiji',
            'dialCode' => '+679',
            'isoCode' => 'FJ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/fj.svg',
          ],
          72 => [
            'name' => 'Finland',
            'dialCode' => '+358',
            'isoCode' => 'FI',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/fi.svg',
          ],
          73 => [
            'name' => 'France',
            'dialCode' => '+33',
            'isoCode' => 'FR',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/fr.svg',
          ],
          74 => [
            'name' => 'French Guiana',
            'dialCode' => '+594',
            'isoCode' => 'GF',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gf.svg',
          ],
          75 => [
            'name' => 'French Polynesia',
            'dialCode' => '+689',
            'isoCode' => 'PF',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/pf.svg',
          ],
          76 => [
            'name' => 'Gabon',
            'dialCode' => '+241',
            'isoCode' => 'GA',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ga.svg',
          ],
          77 => [
            'name' => 'Gambia',
            'dialCode' => '+220',
            'isoCode' => 'GM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gm.svg',
          ],
          78 => [
            'name' => 'Georgia',
            'dialCode' => '+995',
            'isoCode' => 'GE',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ge.svg',
          ],
          79 => [
            'name' => 'Germany',
            'dialCode' => '+49',
            'isoCode' => 'DE',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/de.svg',
          ],
          80 => [
            'name' => 'Ghana',
            'dialCode' => '+233',
            'isoCode' => 'GH',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gh.svg',
          ],
          81 => [
            'name' => 'Gibraltar',
            'dialCode' => '+350',
            'isoCode' => 'GI',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gi.svg',
          ],
          82 => [
            'name' => 'Greece',
            'dialCode' => '+30',
            'isoCode' => 'GR',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gr.svg',
          ],
          83 => [
            'name' => 'Greenland',
            'dialCode' => '+299',
            'isoCode' => 'GL',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gl.svg',
          ],
          84 => [
            'name' => 'Grenada',
            'dialCode' => '+1473',
            'isoCode' => 'GD',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gd.svg',
          ],
          85 => [
            'name' => 'Guadeloupe',
            'dialCode' => '+590',
            'isoCode' => 'GP',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gp.svg',
          ],
          86 => [
            'name' => 'Guam',
            'dialCode' => '+1671',
            'isoCode' => 'GU',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gu.svg',
          ],
          87 => [
            'name' => 'Guatemala',
            'dialCode' => '+502',
            'isoCode' => 'GT',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gt.svg',
          ],
          88 => [
            'name' => 'Guernsey',
            'dialCode' => '+44',
            'isoCode' => 'GG',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gg.svg',
          ],
          89 => [
            'name' => 'Guinea',
            'dialCode' => '+224',
            'isoCode' => 'GN',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gn.svg',
          ],
          90 => [
            'name' => 'Guinea-Bissau',
            'dialCode' => '+245',
            'isoCode' => 'GW',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gw.svg',
          ],
          91 => [
            'name' => 'Guyana',
            'dialCode' => '+592',
            'isoCode' => 'GY',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gy.svg',
          ],
          92 => [
            'name' => 'Haiti',
            'dialCode' => '+509',
            'isoCode' => 'HT',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ht.svg',
          ],
          93 => [
            'name' => 'Holy See (Vatican City State)',
            'dialCode' => '+379',
            'isoCode' => 'VA',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/va.svg',
          ],
          94 => [
            'name' => 'Honduras',
            'dialCode' => '+504',
            'isoCode' => 'HN',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/hn.svg',
          ],
          95 => [
            'name' => 'Hong Kong',
            'dialCode' => '+852',
            'isoCode' => 'HK',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/hk.svg',
          ],
          96 => [
            'name' => 'Hungary',
            'dialCode' => '+36',
            'isoCode' => 'HU',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/hu.svg',
          ],
          97 => [
            'name' => 'Iceland',
            'dialCode' => '+354',
            'isoCode' => 'IS',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/is.svg',
          ],
          98 => [
            'name' => 'India',
            'dialCode' => '+91',
            'isoCode' => 'IN',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/in.svg',
          ],
          99 => [
            'name' => 'Indonesia',
            'dialCode' => '+62',
            'isoCode' => 'ID',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/id.svg',
          ],
          100 => [
            'name' => 'Iran',
            'dialCode' => '+98',
            'isoCode' => 'IR',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ir.svg',
          ],
          101 => [
            'name' => 'Iraq',
            'dialCode' => '+964',
            'isoCode' => 'IQ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/iq.svg',
          ],
          102 => [
            'name' => 'Ireland',
            'dialCode' => '+353',
            'isoCode' => 'IE',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ie.svg',
          ],
          103 => [
            'name' => 'Isle of Man',
            'dialCode' => '+44',
            'isoCode' => 'IM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/im.svg',
          ],
          104 => [
            'name' => 'Israel',
            'dialCode' => '+972',
            'isoCode' => 'IL',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/il.svg',
          ],
          105 => [
            'name' => 'Italy',
            'dialCode' => '+39',
            'isoCode' => 'IT',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/it.svg',
          ],
          106 => [
            'name' => 'Ivory Coast / Cote d\'Ivoire',
            'dialCode' => '+225',
            'isoCode' => 'CI',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ci.svg',
          ],
          107 => [
            'name' => 'Jamaica',
            'dialCode' => '+1876',
            'isoCode' => 'JM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/jm.svg',
          ],
          108 => [
            'name' => 'Japan',
            'dialCode' => '+81',
            'isoCode' => 'JP',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/jp.svg',
          ],
          109 => [
            'name' => 'Jersey',
            'dialCode' => '+44',
            'isoCode' => 'JE',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/je.svg',
          ],
          110 => [
            'name' => 'Jordan',
            'dialCode' => '+962',
            'isoCode' => 'JO',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/jo.svg',
          ],
          111 => [
            'name' => 'Kazakhstan',
            'dialCode' => '+77',
            'isoCode' => 'KZ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/kz.svg',
          ],
          112 => [
            'name' => 'Kenya',
            'dialCode' => '+254',
            'isoCode' => 'KE',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ke.svg',
          ],
          113 => [
            'name' => 'Kiribati',
            'dialCode' => '+686',
            'isoCode' => 'KI',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ki.svg',
          ],
          114 => [
            'name' => 'Korea, Democratic People\'s Republic of Korea',
            'dialCode' => '+850',
            'isoCode' => 'KP',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/kp.svg',
          ],
          115 => [
            'name' => 'Korea, Republic of South Korea',
            'dialCode' => '+82',
            'isoCode' => 'KR',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/kr.svg',
          ],
          116 => [
            'name' => 'Kosovo',
            'dialCode' => '+383',
            'isoCode' => 'XK',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/xk.svg',
          ],
          117 => [
            'name' => 'Kuwait',
            'dialCode' => '+965',
            'isoCode' => 'KW',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/kw.svg',
          ],
          118 => [
            'name' => 'Kyrgyzstan',
            'dialCode' => '+996',
            'isoCode' => 'KG',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/kg.svg',
          ],
          119 => [
            'name' => 'Laos',
            'dialCode' => '+856',
            'isoCode' => 'LA',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/la.svg',
          ],
          120 => [
            'name' => 'Latvia',
            'dialCode' => '+371',
            'isoCode' => 'LV',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/lv.svg',
          ],
          121 => [
            'name' => 'Lebanon',
            'dialCode' => '+961',
            'isoCode' => 'LB',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/lb.svg',
          ],
          122 => [
            'name' => 'Lesotho',
            'dialCode' => '+266',
            'isoCode' => 'LS',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ls.svg',
          ],
          123 => [
            'name' => 'Liberia',
            'dialCode' => '+231',
            'isoCode' => 'LR',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/lr.svg',
          ],
          124 => [
            'name' => 'Libya',
            'dialCode' => '+218',
            'isoCode' => 'LY',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ly.svg',
          ],
          125 => [
            'name' => 'Liechtenstein',
            'dialCode' => '+423',
            'isoCode' => 'LI',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/li.svg',
          ],
          126 => [
            'name' => 'Lithuania',
            'dialCode' => '+370',
            'isoCode' => 'LT',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/lt.svg',
          ],
          127 => [
            'name' => 'Luxembourg',
            'dialCode' => '+352',
            'isoCode' => 'LU',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/lu.svg',
          ],
          128 => [
            'name' => 'Macau',
            'dialCode' => '+853',
            'isoCode' => 'MO',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mo.svg',
          ],
          129 => [
            'name' => 'Madagascar',
            'dialCode' => '+261',
            'isoCode' => 'MG',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mg.svg',
          ],
          130 => [
            'name' => 'Malawi',
            'dialCode' => '+265',
            'isoCode' => 'MW',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mw.svg',
          ],
          131 => [
            'name' => 'Malaysia',
            'dialCode' => '+60',
            'isoCode' => 'MY',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/my.svg',
          ],
          132 => [
            'name' => 'Maldives',
            'dialCode' => '+960',
            'isoCode' => 'MV',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mv.svg',
          ],
          133 => [
            'name' => 'Mali',
            'dialCode' => '+223',
            'isoCode' => 'ML',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ml.svg',
          ],
          134 => [
            'name' => 'Malta',
            'dialCode' => '+356',
            'isoCode' => 'MT',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mt.svg',
          ],
          135 => [
            'name' => 'Marshall Islands',
            'dialCode' => '+692',
            'isoCode' => 'MH',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mh.svg',
          ],
          136 => [
            'name' => 'Martinique',
            'dialCode' => '+596',
            'isoCode' => 'MQ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mq.svg',
          ],
          137 => [
            'name' => 'Mauritania',
            'dialCode' => '+222',
            'isoCode' => 'MR',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mr.svg',
          ],
          138 => [
            'name' => 'Mauritius',
            'dialCode' => '+230',
            'isoCode' => 'MU',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mu.svg',
          ],
          139 => [
            'name' => 'Mayotte',
            'dialCode' => '+262',
            'isoCode' => 'YT',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/yt.svg',
          ],
          140 => [
            'name' => 'Mexico',
            'dialCode' => '+52',
            'isoCode' => 'MX',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mx.svg',
          ],
          141 => [
            'name' => 'Micronesia, Federated States of Micronesia',
            'dialCode' => '+691',
            'isoCode' => 'FM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/fm.svg',
          ],
          142 => [
            'name' => 'Moldova',
            'dialCode' => '+373',
            'isoCode' => 'MD',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/md.svg',
          ],
          143 => [
            'name' => 'Monaco',
            'dialCode' => '+377',
            'isoCode' => 'MC',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mc.svg',
          ],
          144 => [
            'name' => 'Mongolia',
            'dialCode' => '+976',
            'isoCode' => 'MN',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mn.svg',
          ],
          145 => [
            'name' => 'Montenegro',
            'dialCode' => '+382',
            'isoCode' => 'ME',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/me.svg',
          ],
          146 => [
            'name' => 'Montserrat',
            'dialCode' => '+1664',
            'isoCode' => 'MS',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ms.svg',
          ],
          147 => [
            'name' => 'Morocco',
            'dialCode' => '+212',
            'isoCode' => 'MA',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ma.svg',
          ],
          148 => [
            'name' => 'Mozambique',
            'dialCode' => '+258',
            'isoCode' => 'MZ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mz.svg',
          ],
          149 => [
            'name' => 'Myanmar',
            'dialCode' => '+95',
            'isoCode' => 'MM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mm.svg',
          ],
          150 => [
            'name' => 'Namibia',
            'dialCode' => '+264',
            'isoCode' => 'NA',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/na.svg',
          ],
          151 => [
            'name' => 'Nauru',
            'dialCode' => '+674',
            'isoCode' => 'NR',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/nr.svg',
          ],
          152 => [
            'name' => 'Nepal',
            'dialCode' => '+977',
            'isoCode' => 'NP',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/np.svg',
          ],
          153 => [
            'name' => 'Netherlands',
            'dialCode' => '+31',
            'isoCode' => 'NL',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/nl.svg',
          ],
          154 => [
            'name' => 'Netherlands Antilles',
            'dialCode' => '+599',
            'isoCode' => 'AN',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/an.svg',
          ],
          155 => [
            'name' => 'New Caledonia',
            'dialCode' => '+687',
            'isoCode' => 'NC',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/nc.svg',
          ],
          156 => [
            'name' => 'New Zealand',
            'dialCode' => '+64',
            'isoCode' => 'NZ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/nz.svg',
          ],
          157 => [
            'name' => 'Nicaragua',
            'dialCode' => '+505',
            'isoCode' => 'NI',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ni.svg',
          ],
          158 => [
            'name' => 'Niger',
            'dialCode' => '+227',
            'isoCode' => 'NE',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ne.svg',
          ],
          159 => [
            'name' => 'Nigeria',
            'dialCode' => '+234',
            'isoCode' => 'NG',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ng.svg',
          ],
          160 => [
            'name' => 'Niue',
            'dialCode' => '+683',
            'isoCode' => 'NU',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/nu.svg',
          ],
          161 => [
            'name' => 'Norfolk Island',
            'dialCode' => '+672',
            'isoCode' => 'NF',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/nf.svg',
          ],
          162 => [
            'name' => 'North Macedonia',
            'dialCode' => '+389',
            'isoCode' => 'MK',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mk.svg',
          ],
          163 => [
            'name' => 'Northern Mariana Islands',
            'dialCode' => '+1670',
            'isoCode' => 'MP',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mp.svg',
          ],
          164 => [
            'name' => 'Norway',
            'dialCode' => '+47',
            'isoCode' => 'NO',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/no.svg',
          ],
          165 => [
            'name' => 'Oman',
            'dialCode' => '+968',
            'isoCode' => 'OM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/om.svg',
          ],
          166 => [
            'name' => 'Pakistan',
            'dialCode' => '+92',
            'isoCode' => 'PK',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/pk.svg',
          ],
          167 => [
            'name' => 'Palau',
            'dialCode' => '+680',
            'isoCode' => 'PW',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/pw.svg',
          ],
          168 => [
            'name' => 'Palestine',
            'dialCode' => '+970',
            'isoCode' => 'PS',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ps.svg',
          ],
          169 => [
            'name' => 'Panama',
            'dialCode' => '+507',
            'isoCode' => 'PA',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/pa.svg',
          ],
          170 => [
            'name' => 'Papua New Guinea',
            'dialCode' => '+675',
            'isoCode' => 'PG',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/pg.svg',
          ],
          171 => [
            'name' => 'Paraguay',
            'dialCode' => '+595',
            'isoCode' => 'PY',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/py.svg',
          ],
          172 => [
            'name' => 'Peru',
            'dialCode' => '+51',
            'isoCode' => 'PE',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/pe.svg',
          ],
          173 => [
            'name' => 'Philippines',
            'dialCode' => '+63',
            'isoCode' => 'PH',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ph.svg',
          ],
          174 => [
            'name' => 'Pitcairn',
            'dialCode' => '+872',
            'isoCode' => 'PN',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/pn.svg',
          ],
          175 => [
            'name' => 'Poland',
            'dialCode' => '+48',
            'isoCode' => 'PL',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/pl.svg',
          ],
          176 => [
            'name' => 'Portugal',
            'dialCode' => '+351',
            'isoCode' => 'PT',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/pt.svg',
          ],
          177 => [
            'name' => 'Puerto Rico',
            'dialCode' => '+1939',
            'isoCode' => 'PR',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/pr.svg',
          ],
          178 => [
            'name' => 'Qatar',
            'dialCode' => '+974',
            'isoCode' => 'QA',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/qa.svg',
          ],
          179 => [
            'name' => 'Reunion',
            'dialCode' => '+262',
            'isoCode' => 'RE',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/re.svg',
          ],
          180 => [
            'name' => 'Romania',
            'dialCode' => '+40',
            'isoCode' => 'RO',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ro.svg',
          ],
          181 => [
            'name' => 'Russia',
            'dialCode' => '+7',
            'isoCode' => 'RU',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ru.svg',
          ],
          182 => [
            'name' => 'Rwanda',
            'dialCode' => '+250',
            'isoCode' => 'RW',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/rw.svg',
          ],
          183 => [
            'name' => 'Saint Barthelemy',
            'dialCode' => '+590',
            'isoCode' => 'BL',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/bl.svg',
          ],
          184 => [
            'name' => 'Saint Helena, Ascension and Tristan Da Cunha',
            'dialCode' => '+290',
            'isoCode' => 'SH',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sh.svg',
          ],
          185 => [
            'name' => 'Saint Kitts and Nevis',
            'dialCode' => '+1869',
            'isoCode' => 'KN',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/kn.svg',
          ],
          186 => [
            'name' => 'Saint Lucia',
            'dialCode' => '+1758',
            'isoCode' => 'LC',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/lc.svg',
          ],
          187 => [
            'name' => 'Saint Martin',
            'dialCode' => '+590',
            'isoCode' => 'MF',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/mf.svg',
          ],
          188 => [
            'name' => 'Saint Pierre and Miquelon',
            'dialCode' => '+508',
            'isoCode' => 'PM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/pm.svg',
          ],
          189 => [
            'name' => 'Saint Vincent and the Grenadines',
            'dialCode' => '+1784',
            'isoCode' => 'VC',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/vc.svg',
          ],
          190 => [
            'name' => 'Samoa',
            'dialCode' => '+685',
            'isoCode' => 'WS',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ws.svg',
          ],
          191 => [
            'name' => 'San Marino',
            'dialCode' => '+378',
            'isoCode' => 'SM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sm.svg',
          ],
          192 => [
            'name' => 'Sao Tome and Principe',
            'dialCode' => '+239',
            'isoCode' => 'ST',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/st.svg',
          ],
          193 => [
            'name' => 'Saudi Arabia',
            'dialCode' => '+966',
            'isoCode' => 'SA',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sa.svg',
          ],
          194 => [
            'name' => 'Senegal',
            'dialCode' => '+221',
            'isoCode' => 'SN',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sn.svg',
          ],
          195 => [
            'name' => 'Serbia',
            'dialCode' => '+381',
            'isoCode' => 'RS',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/rs.svg',
          ],
          196 => [
            'name' => 'Seychelles',
            'dialCode' => '+248',
            'isoCode' => 'SC',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sc.svg',
          ],
          197 => [
            'name' => 'Sierra Leone',
            'dialCode' => '+232',
            'isoCode' => 'SL',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sl.svg',
          ],
          198 => [
            'name' => 'Singapore',
            'dialCode' => '+65',
            'isoCode' => 'SG',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sg.svg',
          ],
          199 => [
            'name' => 'Sint Maarten',
            'dialCode' => '+1721',
            'isoCode' => 'SX',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sx.svg',
          ],
          200 => [
            'name' => 'Slovakia',
            'dialCode' => '+421',
            'isoCode' => 'SK',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sk.svg',
          ],
          201 => [
            'name' => 'Slovenia',
            'dialCode' => '+386',
            'isoCode' => 'SI',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/si.svg',
          ],
          202 => [
            'name' => 'Solomon Islands',
            'dialCode' => '+677',
            'isoCode' => 'SB',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sb.svg',
          ],
          203 => [
            'name' => 'Somalia',
            'dialCode' => '+252',
            'isoCode' => 'SO',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/so.svg',
          ],
          204 => [
            'name' => 'South Africa',
            'dialCode' => '+27',
            'isoCode' => 'ZA',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/za.svg',
          ],
          205 => [
            'name' => 'South Georgia and the South Sandwich Islands',
            'dialCode' => '+500',
            'isoCode' => 'GS',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gs.svg',
          ],
          206 => [
            'name' => 'South Sudan',
            'dialCode' => '+211',
            'isoCode' => 'SS',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ss.svg',
          ],
          207 => [
            'name' => 'Spain',
            'dialCode' => '+34',
            'isoCode' => 'ES',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/es.svg',
          ],
          208 => [
            'name' => 'Sri Lanka',
            'dialCode' => '+94',
            'isoCode' => 'LK',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/lk.svg',
          ],
          209 => [
            'name' => 'Sudan',
            'dialCode' => '+249',
            'isoCode' => 'SD',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sd.svg',
          ],
          210 => [
            'name' => 'Suriname',
            'dialCode' => '+597',
            'isoCode' => 'SR',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sr.svg',
          ],
          211 => [
            'name' => 'Svalbard and Jan Mayen',
            'dialCode' => '+47',
            'isoCode' => 'SJ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sj.svg',
          ],
          212 => [
            'name' => 'Sweden',
            'dialCode' => '+46',
            'isoCode' => 'SE',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/se.svg',
          ],
          213 => [
            'name' => 'Switzerland',
            'dialCode' => '+41',
            'isoCode' => 'CH',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ch.svg',
          ],
          214 => [
            'name' => 'Syrian Arab Republic',
            'dialCode' => '+963',
            'isoCode' => 'SY',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/sy.svg',
          ],
          215 => [
            'name' => 'Taiwan',
            'dialCode' => '+886',
            'isoCode' => 'TW',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/tw.svg',
          ],
          216 => [
            'name' => 'Tajikistan',
            'dialCode' => '+992',
            'isoCode' => 'TJ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/tj.svg',
          ],
          217 => [
            'name' => 'Tanzania, United Republic of Tanzania',
            'dialCode' => '+255',
            'isoCode' => 'TZ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/tz.svg',
          ],
          218 => [
            'name' => 'Thailand',
            'dialCode' => '+66',
            'isoCode' => 'TH',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/th.svg',
          ],
          219 => [
            'name' => 'Timor-Leste',
            'dialCode' => '+670',
            'isoCode' => 'TL',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/tl.svg',
          ],
          220 => [
            'name' => 'Togo',
            'dialCode' => '+228',
            'isoCode' => 'TG',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/tg.svg',
          ],
          221 => [
            'name' => 'Tokelau',
            'dialCode' => '+690',
            'isoCode' => 'TK',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/tk.svg',
          ],
          222 => [
            'name' => 'Tonga',
            'dialCode' => '+676',
            'isoCode' => 'TO',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/to.svg',
          ],
          223 => [
            'name' => 'Trinidad and Tobago',
            'dialCode' => '+1868',
            'isoCode' => 'TT',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/tt.svg',
          ],
          224 => [
            'name' => 'Tunisia',
            'dialCode' => '+216',
            'isoCode' => 'TN',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/tn.svg',
          ],
          225 => [
            'name' => 'Turkey',
            'dialCode' => '+90',
            'isoCode' => 'TR',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/tr.svg',
          ],
          226 => [
            'name' => 'Turkmenistan',
            'dialCode' => '+993',
            'isoCode' => 'TM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/tm.svg',
          ],
          227 => [
            'name' => 'Turks and Caicos Islands',
            'dialCode' => '+1649',
            'isoCode' => 'TC',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/tc.svg',
          ],
          228 => [
            'name' => 'Tuvalu',
            'dialCode' => '+688',
            'isoCode' => 'TV',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/tv.svg',
          ],
          229 => [
            'name' => 'Uganda',
            'dialCode' => '+256',
            'isoCode' => 'UG',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ug.svg',
          ],
          230 => [
            'name' => 'Ukraine',
            'dialCode' => '+380',
            'isoCode' => 'UA',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ua.svg',
          ],
          231 => [
            'name' => 'United Arab Emirates',
            'dialCode' => '+971',
            'isoCode' => 'AE',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ae.svg',
          ],
          232 => [
            'name' => 'United Kingdom',
            'dialCode' => '+44',
            'isoCode' => 'GB',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/gb.svg',
          ],
          233 => [
            'name' => 'United States',
            'dialCode' => '+1',
            'isoCode' => 'US',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/us.svg',
          ],
          234 => [
            'name' => 'United States Minor Outlying Islands',
            'dialCode' => '+246',
            'isoCode' => 'UMI',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/umi.svg',
          ],
          235 => [
            'name' => 'Uruguay',
            'dialCode' => '+598',
            'isoCode' => 'UY',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/uy.svg',
          ],
          236 => [
            'name' => 'Uzbekistan',
            'dialCode' => '+998',
            'isoCode' => 'UZ',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/uz.svg',
          ],
          237 => [
            'name' => 'Vanuatu',
            'dialCode' => '+678',
            'isoCode' => 'VU',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/vu.svg',
          ],
          238 => [
            'name' => 'Venezuela, Bolivarian Republic of Venezuela',
            'dialCode' => '+58',
            'isoCode' => 'VE',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ve.svg',
          ],
          239 => [
            'name' => 'Vietnam',
            'dialCode' => '+84',
            'isoCode' => 'VN',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/vn.svg',
          ],
          240 => [
            'name' => 'Virgin Islands, British',
            'dialCode' => '+1284',
            'isoCode' => 'VG',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/vg.svg',
          ],
          241 => [
            'name' => 'Virgin Islands, U.S.',
            'dialCode' => '+1340',
            'isoCode' => 'VI',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/vi.svg',
          ],
          242 => [
            'name' => 'Wallis and Futuna',
            'dialCode' => '+681',
            'isoCode' => 'WF',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/wf.svg',
          ],
          243 => [
            'name' => 'Yemen',
            'dialCode' => '+967',
            'isoCode' => 'YE',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/ye.svg',
          ],
          244 => [
            'name' => 'Zambia',
            'dialCode' => '+260',
            'isoCode' => 'ZM',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/zm.svg',
          ],
          245 => [
            'name' => 'Zimbabwe',
            'dialCode' => '+263',
            'isoCode' => 'ZW',
            'flag' => 'https://cdn.kcak11.com/CountryFlags/countries/zw.svg',
          ],
      ];


      foreach ($countries as $c) {
        Country::create([
          'name'       => $c['name'],
          'dial_code'  => $c['dialCode'],
          'iso_code'   => $c['isoCode'],
          'flag_image' => $c['flag']
        ]);
      }
    }
}
